[tool.poetry]
name = "YOUR_MODULE_NAME"
version = "0.1.0"
description = ""
authors = ["YOUR NAME <YOUR@EMAIL>", 
    "Aarhus Stadsarkiv <stadsarkiv@aarhus.dk>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://stadsarkiv.aarhus.dk/"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8"
black = "^19.10b0"
flake8 = "^3.7.9"
mypy = "^0.770"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

